### ISSUE TITLE
Bewegende controller

### ISSUE THREAD

**Issue by DarkBlueSheep** [SeanVisser1998/parkeergarage-2017-2018#4]
De controllers bewegen soms naar links / rechts (vooral zichtbaar als je de slider helemaal naar links zet)

**Comment by SeanVisser1998** [comment]
Oorzaak: Komt omdat de JLabel langer wordt als de tijd ook 'groter' wordt :)
Mogelijke oplossing: Haal de JLabel uit de contentPane van de controller :D

**Comment by SeanVisser1998** [comment]
Fixed.
